# Site settings
title: Wade Wegner
email: your_email@example.com
author: Wade Wegner
description: "From the whiteboard to the keyboard."
baseurl: ""
url: "http://www.wadewegner.com"

# Build settings
encoding: utf-8
markdown: redcarpet #kramdown
paginate: 5
permalink: /:year/:month/:title/

# Social
google_analytics: UA-1174672-2

# Sitemap
sitemap:
  lastmod: 2014-09-07
  priority: 0.7
  changefreq: monthly
  exclude: 'yes'